# Generated by Django 2.1.3 on 2018-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
