# Generated by Django 2.1.2 on 2018-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image_filename',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
