# Generated by Django 2.1.2 on 2018-12-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_quizpage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='number',
        ),
    ]
