# Generated by Django 2.1.2 on 2018-12-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpage',
            old_name='page_number',
            new_name='quiz_number',
        ),
    ]
