# Generated by Django 2.1.2 on 2018-12-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20181219_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['pk']},
        ),
    ]
