# Generated by Django 2.1.2 on 2018-12-06 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DE', 'Description'), ('CO', '"most correct" vote'), ('CR', '"most creative" vote')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('voted_correct', models.SmallIntegerField(default=0)),
                ('voted_creative', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
                ('publish', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three')], default='1', max_length=1)),
                ('correct_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsit.Object'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsit.Object'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
