# Generated by Django 2.1.2 on 2018-12-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['number']},
        ),
    ]
