# Generated by Django 2.1.3 on 2018-12-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsit', '0002_auto_20181206_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='voted_correct',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='description',
            name='voted_creative',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='type',
            field=models.CharField(choices=[('DE', 'Description'), ('VO', 'Vote')], max_length=2),
        ),
    ]
